apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-env-secret
  namespace: monitoring
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: grafana-env-secret
    creationPolicy: Owner
  data:
    - secretKey: DISCORD_WEBHOOK_URL
      remoteRef:
        key: moongcheap-develop-monitoring-discord-secret