apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-notifications-discord-secret
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: argocd-notifications-secret
    creationPolicy: Merge
  data:
    - secretKey: discord-webhook-url
      remoteRef:
        key: moongcheap-develop-argocd-discord-secret
        property: discord-webhook-url
