apiVersion: external-secrets.io/v1
kind: ExternalSecret

metadata:
  name: backend-env
  namespace: moongcheap-develop

spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore

  target:
    name: backend-env
    creationPolicy: Owner

    template:
      engineVersion: v2
      data:
        DB_URL: "jdbc:postgresql://{{ .host }}:{{ .port }}/{{ .dbname }}"
        DB_USERNAME: "{{ .username }}"
        DB_PASSWORD: "{{ .password }}"

        KAKAO_CLIENT_ID: "{{ .KAKAO_CLIENT_ID }}"
        KAKAO_CLIENT_SECRET: "{{ .KAKAO_CLIENT_SECRET }}"
        GOOGLE_CLIENT_ID: "{{ .GOOGLE_CLIENT_ID }}"
        GOOGLE_CLIENT_SECRET: "{{ .GOOGLE_CLIENT_SECRET }}"

        MOONGCHEAP_ENC_PASSWORD: "{{ .MOONGCHEAP_ENC_PASSWORD }}"
        MOONGCHEAP_ENC_SALT: "{{ .MOONGCHEAP_ENC_SALT }}"
        MOONGCHEAP_INTERNAL_API_KEY: "{{ .MOONGCHEAP_INTERNAL_API_KEY }}"
        SELLER_ANALYSIS_INTERNAL_KEY: "{{ .SELLER_ANALYSIS_INTERNAL_KEY }}"

  dataFrom:
    - extract:
        key: moongcheap-develop-db-secret

    - extract:
        key: moongcheap-develop-be-oauth-secret