apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: jenkins-admin-secret
  namespace: jenkins
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: jenkins-admin-secret
    creationPolicy: Owner
  data:
    - secretKey: jenkins-admin-user
      remoteRef:
        key: moongcheap-develop-jenkins-admin-secret
        property: jenkins-admin-user
    - secretKey: jenkins-admin-password
      remoteRef:
        key: moongcheap-develop-jenkins-admin-secret
        property: jenkins-admin-password
