#!/usr/bin/env bash
# schedule.csv → 현재 사용자 crontab의 MoongCheap 관리 구간만 갱신한다.
#   - Marker(# BEGIN/END MOONGCHEAP MANAGED CRON) 사이만 교체, 그 밖의 항목은 그대로 보존
#   - CSV 검증에 하나라도 실패하면 crontab을 건드리지 않고 종료
#   - 적용 전 기존 crontab을 ~/.moongcheap/crontab-backup/ 에 백업
#   - sync-repo.sh 자체의 cron(*/5 sync-repo.sh)은 이 구간 밖에 사람이 직접 등록한다
# 수동 실행: /opt/moongcheap/MoongCheap-Cloud/terraform/scripts/mgmt/update-cron.sh
# 권한: 일반 사용자(자기 crontab). sudo 불필요.
set -euo pipefail

# shellcheck source=common.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/common.sh"
trap on_error ERR
trap on_exit EXIT

acquire_lock update-cron
info "시작: crontab 갱신 (schedule=${SCHEDULE_FILE})"
require_cmd crontab
require_file "${SCHEDULE_FILE}"

# ── CSV 파싱 (common.sh parse_schedule_file — 한 줄이라도 잘못되면 여기서 종료, crontab 무변경) ──
rows="$(parse_schedule_file "${SCHEDULE_FILE}")"

declare -a CRON_LINES=()
enabled_count=0
disabled_count=0
while IFS=$'\t' read -r action minute hour dow enabled time days memo; do
  if [[ "${enabled}" != "true" ]]; then
    disabled_count=$((disabled_count + 1))
    info "건너뜀(enabled=false): ${action} ${time} ${days}${memo:+ — ${memo}}"
    continue
  fi
  target="${SCRIPT_DIR}/${action}-infra.sh"
  [[ -x "${target}" ]] || die "실행 파일 없음 또는 실행 권한 없음: ${target} (chmod +x 확인)"
  CRON_LINES+=("# ${action} ${time} ${days}${memo:+ — ${memo}}"$'\n'"${minute} ${hour} * * ${dow} ${target}")
  enabled_count=$((enabled_count + 1))
done <<< "${rows}"

info "CSV 검증 통과: 활성 ${enabled_count}건, 비활성 ${disabled_count}건"
(( enabled_count > 0 )) || warn "활성 스케줄이 0건 — Open/Close cron이 비게 됨(의도한 것인지 확인)"

# ── 기존 crontab 읽기·백업 ────────────────────────────────────────────────
current="$(crontab -l 2>/dev/null || true)"

begin_n="$(printf '%s\n' "${current}" | grep -c -Fx "${CRON_MARKER_BEGIN}" || true)"
end_n="$(printf '%s\n' "${current}" | grep -c -Fx "${CRON_MARKER_END}" || true)"
if (( begin_n != end_n || begin_n > 1 )); then
  die "crontab의 MoongCheap Marker가 손상됨(BEGIN=${begin_n}, END=${end_n}). 수동으로 정리 후 재실행: crontab -e"
fi

# ── 새 crontab 조립 ───────────────────────────────────────────────────────
# Marker 밖 내용만 남긴다(다른 사람이 등록한 항목 보존).
outside="$(printf '%s\n' "${current}" \
  | awk -v b="${CRON_MARKER_BEGIN}" -v e="${CRON_MARKER_END}" '
      $0 == b { skip = 1; next }
      $0 == e { skip = 0; next }
      !skip   { print }
    ')"

managed_block="${CRON_MARKER_BEGIN}
# generated by update-cron.sh from terraform/scripts/mgmt/schedule.csv ($(date --iso-8601=seconds))
# 직접 수정 금지 — schedule.csv를 고쳐 develop에 머지하면 sync-repo.sh가 반영한다
# 시각은 서버 timezone 기준(Asia/Seoul로 설정돼 있어야 함 — setup guide 참고)"
for line in ${CRON_LINES[@]+"${CRON_LINES[@]}"}; do
  managed_block+=$'\n'"${line}"
done
managed_block+=$'\n'"${CRON_MARKER_END}"

new_crontab="$(printf '%s\n' "${outside}" | sed -e :a -e '/^\n*$/{$d;N;ba' -e '}')"
if [[ -n "${new_crontab}" ]]; then
  new_crontab+=$'\n\n'"${managed_block}"
else
  new_crontab="${managed_block}"
fi

# 타임스탬프 주석만 다른 경우는 변경으로 치지 않는다.
strip_ts() { grep -v '^# generated by update-cron.sh' || true; }
if [[ "$(printf '%s\n' "${current}" | strip_ts)" == "$(printf '%s\n' "${new_crontab}" | strip_ts)" ]]; then
  info "crontab 변경 없음 — 적용 생략"
  exit 0
fi

mkdir -p "${CRON_BACKUP_DIR}"
backup_file="${CRON_BACKUP_DIR}/crontab-$(date +%Y%m%d-%H%M%S)-$$.bak"
printf '%s\n' "${current}" > "${backup_file}"
info "기존 crontab 백업: ${backup_file}"

# crontab -는 문법 오류 시 기존 crontab을 건드리지 않고 실패한다.
printf '%s\n' "${new_crontab}" | crontab - || die "crontab 적용 실패 — 기존 crontab 유지됨. 백업: ${backup_file}"

info "crontab 적용 완료. MoongCheap 관리 구간:"
printf '%s\n' "${managed_block}" | while IFS= read -r l; do info "  ${l}"; done
