# gitops/charts/moongcheap-service/templates/scaledobject.yaml
{{- if .Values.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "moongcheap-service.fullname" . }}
  labels:
    {{- include "moongcheap-service.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "moongcheap-service.fullname" . }}

  minReplicaCount: {{ .Values.keda.minReplicaCount }}
  maxReplicaCount: {{ .Values.keda.maxReplicaCount }}
  pollingInterval: {{ .Values.keda.pollingInterval }}
  cooldownPeriod: {{ .Values.keda.cooldownPeriod }}

  {{- with .Values.keda.advanced }}
  advanced:
    {{- toYaml . | nindent 4 }}
  {{- end }}

  triggers:
    {{- range .Values.keda.triggers }}
    - type: prometheus
      metadata:
        serverAddress: {{ .serverAddress }}
        query: {{ .query | quote }}
        threshold: {{ .threshold | quote }}
        {{- if .activationThreshold }}
        activationThreshold: {{ .activationThreshold | quote }}
        {{- end }}
    {{- end }}
{{- end }}