{{- if eq .Values.workload.kind "CronJob" }}
apiVersion: v1
kind: ServiceAccount

metadata:
  name: {{ .Values.cronjob.serviceAccountName }}
  labels:
    {{- include "moongcheap-service.labels" . | nindent 4 }}
    app.kubernetes.io/component: batch

automountServiceAccountToken: false
{{- end }}